a = input("Digite algo")
print(f"O tipo primitivo desse valor é {type(a)}")
print(f'Tem espacos? {a.isspace()}")
print(f'É um numero? {a.isnumeric}')
print(f'É alfabetico? {a.isalpha}')
print(f'É alfanumerico? {a.isalnum}')
print(f'Está em maiusculas? {a.isupper}')
print(f'Está em minusculas? {a.islower}')
print(f'Esta capitalizado? {a.istitle}')
